OBJS = Fibonacci.o
CC = g++
DEBUG = -g
CFLAGS = -Wall -c $(DEBUG)
LFLAGS = -Wall $(DEBUG)

Fibonacci : $(OBJS)
		   $(CC) $(LFLAGS) $(OBJS) -o Fibonacci

Fibonacci.o : Fibonacci.cpp
			 $(CC) $(CFLAGS) Fibonacci.cpp
			 
clean:
	\rm *.o *~ Fibonacci